url: https://ger-unicamp.github.io/semana-robotica-unicamp/
baseurl: 

# Site settings
title: Semana da Robótica - Unicamp
email: semana.robotica.unicamp@gmail.com
description: "Primeiro evento de divulgação de robótica da Unicamp"


# Team names, titles and social links
people:
- name: GER Unicamp
  pic: 1
  position: Grupo de estudos de robótica autônoma
  social:
    - title: instagram
      url: https://www.instagram.com/ger.unicamp/
    - title: facebook
      url: https://www.facebook.com/unicampger/
- name: Phoenix Unicamp
  pic: 2
  position: TODO 
  social: 
    - title: instagram
      url: TODO
    - title: facebook
      url: TODO
- name: IEEE Unicamp
  pic: 3
  position: TODO 
  social: 
    - title: instagram
      url: TODO
    - title: facebook
      url: TODO

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb


# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
